"""baseline

Revision ID: ebb53dc90cdf
Revises: 
Create Date: 2026-07-22 22:12:07.310446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb53dc90cdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_code',
    sa.Column('id_auth_code', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_auth_code'),
    schema='core'
    )
    op.create_index(op.f('ix_core_auth_code_email'), 'auth_code', ['email'], unique=False, schema='core')
    op.create_table('usuario',
    sa.Column('id_usuario', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    schema='core'
    )
    op.create_table('gasto_categoria',
    sa.Column('id_gasto_categoria', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=False),
    sa.Column('mes_ano', sa.Date(), nullable=False),
    sa.Column('total_gasto', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('qtd_itens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_gasto_categoria'),
    schema='analytics'
    )
    op.create_table('gasto_mensal',
    sa.Column('id_gasto_mensal', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('mes_ano', sa.Date(), nullable=False),
    sa.Column('total_gasto', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('qtd_transacoes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('qtd_notas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_gasto_mensal'),
    schema='analytics'
    )
    op.create_table('nota_analytics',
    sa.Column('id_nota_analytics', sa.BigInteger(), nullable=False),
    sa.Column('id_extracao', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('empresa', sa.Text(), nullable=True),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('serie', sa.Text(), nullable=True),
    sa.Column('emissao', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('qtd_total_itens', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_importacao', sa.BigInteger(), nullable=True),
    sa.Column('id_nota_raw', sa.BigInteger(), nullable=True),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_nota_analytics'),
    schema='analytics'
    )
    op.create_table('extracao',
    sa.Column('id_extracao', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'ERROR', name='extracao_status', schema='core'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reprocess_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('reprocessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_extracao'),
    schema='core'
    )
    op.create_table('item_nota_analytics',
    sa.Column('id_item_analytics', sa.BigInteger(), nullable=False),
    sa.Column('id_nota_analytics', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unidade', sa.Text(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_nota_analytics'], ['analytics.nota_analytics.id_nota_analytics'], ),
    sa.PrimaryKeyConstraint('id_item_analytics'),
    schema='analytics'
    )
    op.create_table('extracao_step',
    sa.Column('id_step', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id_extracao', sa.BigInteger(), nullable=False),
    sa.Column('etapa', sa.Enum('RAW_IMPORT', 'STAGING', 'ANALYTICS', 'COMPLETE', name='pipeline_step', schema='core'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'ERROR', name='step_status', schema='core'), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_extracao'], ['core.extracao.id_extracao'], ),
    sa.PrimaryKeyConstraint('id_step'),
    schema='core'
    )
    op.create_table('importacao',
    sa.Column('id_importacao', sa.BigInteger(), nullable=False),
    sa.Column('storage_bucket', sa.String(length=63), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('storage_filename', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_extracao', sa.BigInteger(), nullable=True),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_extracao'], ['core.extracao.id_extracao'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_importacao'),
    schema='raw'
    )
    op.create_table('fatura',
    sa.Column('id_fatura', sa.BigInteger(), nullable=False),
    sa.Column('banco', sa.String(length=50), nullable=False),
    sa.Column('nome_titular', sa.Text(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('id_importacao', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_importacao'], ['raw.importacao.id_importacao'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_fatura'),
    schema='raw'
    )
    op.create_table('nota',
    sa.Column('id_nota', sa.BigInteger(), nullable=False),
    sa.Column('empresa', sa.Text(), nullable=False),
    sa.Column('chave', sa.String(length=44), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('serie', sa.Text(), nullable=False),
    sa.Column('emissao', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qtd_total_itens', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('id_fatura', sa.BigInteger(), nullable=True),
    sa.Column('id_importacao', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_fatura'], ['raw.fatura.id_fatura'], ),
    sa.ForeignKeyConstraint(['id_importacao'], ['raw.importacao.id_importacao'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_nota'),
    schema='raw'
    )
    op.create_table('transacao',
    sa.Column('id_transacao', sa.BigInteger(), nullable=False),
    sa.Column('data_realizacao', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('final_cartao', sa.String(length=4), nullable=True),
    sa.Column('parcela', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_fatura', sa.BigInteger(), nullable=True),
    sa.Column('id_importacao', sa.BigInteger(), nullable=True),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_fatura'], ['raw.fatura.id_fatura'], ),
    sa.ForeignKeyConstraint(['id_importacao'], ['raw.importacao.id_importacao'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_transacao'),
    schema='raw'
    )
    op.create_table('item_nota',
    sa.Column('id_item_nota', sa.BigInteger(), nullable=False),
    sa.Column('item_codigo', sa.Text(), nullable=True),
    sa.Column('item_descricao', sa.Text(), nullable=False),
    sa.Column('item_quantidade', sa.Numeric(precision=10, scale=3), server_default='1', nullable=False),
    sa.Column('item_tipo_unidade', sa.Text(), server_default='UN', nullable=True),
    sa.Column('item_valor_unidade', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('item_valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_nota', sa.BigInteger(), nullable=True),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_nota'], ['raw.nota.id_nota'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_item_nota'),
    schema='raw'
    )
    op.create_table('nota_normalizada',
    sa.Column('id_nota_normalizada', sa.BigInteger(), nullable=False),
    sa.Column('id_nota', sa.BigInteger(), nullable=True),
    sa.Column('id_importacao', sa.BigInteger(), nullable=True),
    sa.Column('id_extracao', sa.BigInteger(), nullable=True),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('emitente', sa.Text(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=False),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_nota'], ['raw.nota.id_nota'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_nota_normalizada'),
    schema='staging'
    )
    op.create_table('item_normalizado',
    sa.Column('id_item_normalizado', sa.BigInteger(), nullable=False),
    sa.Column('id_item_nota', sa.BigInteger(), nullable=True),
    sa.Column('id_nota_normalizada', sa.BigInteger(), nullable=True),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_item_nota'], ['raw.item_nota.id_item_nota'], ),
    sa.ForeignKeyConstraint(['id_nota_normalizada'], ['staging.nota_normalizada.id_nota_normalizada'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['core.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_item_normalizado'),
    schema='staging'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_normalizado', schema='staging')
    op.drop_table('nota_normalizada', schema='staging')
    op.drop_table('item_nota', schema='raw')
    op.drop_table('transacao', schema='raw')
    op.drop_table('nota', schema='raw')
    op.drop_table('fatura', schema='raw')
    op.drop_table('importacao', schema='raw')
    op.drop_table('extracao_step', schema='core')
    op.drop_table('item_nota_analytics', schema='analytics')
    op.drop_table('extracao', schema='core')
    op.drop_table('nota_analytics', schema='analytics')
    op.drop_table('gasto_mensal', schema='analytics')
    op.drop_table('gasto_categoria', schema='analytics')
    op.drop_table('usuario', schema='core')
    op.drop_index(op.f('ix_core_auth_code_email'), table_name='auth_code', schema='core')
    op.drop_table('auth_code', schema='core')
    op.execute("DROP TYPE IF EXISTS core.extracao_status CASCADE")
    op.execute("DROP TYPE IF EXISTS core.pipeline_step CASCADE")
    op.execute("DROP TYPE IF EXISTS core.step_status CASCADE")
    # ### end Alembic commands ###
